server:
  port: 10000
spring:
  application:
    name: product-server
  #连接数据库
  datasource:
    url: jdbc:mysql://localhost:3306/shuzhai_book?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://peer1:9997/eureka/,http://peer2:9998/eureka/,http://peer3:9999/eureka/
#配置mybatis自动对bean进行注入
mybatis:
  type-aliases-package: com.book.shuzhai.entity
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true #下划线自动转驼峰
  mapper-locations: classpath:mapper/*Mapper.xml