server:
  port: 9996
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://peer1:9997/eureka/,http://peer1:9998/eureka/,http://peer1:9999/eureka/
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000