server:
  port: 9996
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://peer1:9997/eureka/,http://peer1:9998/eureka/,http://peer1:9999/eureka/
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  add-host-header: true # 携带请求头本身的head头信息
  sensitive-headers: null # 配置禁止使用的头部信息，这里设置为null，否则set-cookie无效

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
